// Automatically generated by astro-icon
// 001a1ccebb4bfa874cce071296b7167baf197ac1b43baf1f725af5a705835151

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "calendar"
		| "clock"
		| "pen"
		| "person";
}